### ISSUE TITLE
Crash after running for a while "overflow when subtracting durations"

### ISSUE THREAD

**Issue by mtrolley** [cjbassi/ytop#34]
Several times I've had ytop left running and came back to find it crashed with this backtrace:

```
Backtrace (most recent call first):
  File "src/libcore/option.rs", line 1185, in core::option::expect_failed
  File "src/libcore/option.rs", line 345, in core::option::Option<T>::expect
  File "src/libcore/time.rs", line 744, in <core::time::Duration as core::ops::arith::Sub>::sub
  File "<unknown>", line 0, in psutil::process::process::Process::cpu_percent
  File "<unknown>", line 0, in <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
  File "<unknown>", line 0, in <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  File "<unknown>", line 0, in <ytop::widgets::proc::ProcWidget as ytop::update::UpdatableWidget>::update
  File "<unknown>", line 0, in ytop::update::update_widgets
  File "<unknown>", line 0, in ytop::main
  File "<unknown>", line 0, in std::rt::lang_start::{{closure}}
  File "src/libstd/rt.rs", line 48, in std::rt::lang_start_internal::{{closure}}
  File "src/libstd/panicking.rs", line 287, in std::panicking::try::do_call
  File "src/libpanic_unwind/lib.rs", line 78, in __rust_maybe_catch_panic
  File "src/libstd/panicking.rs", line 265, in std::panicking::try
  File "src/libstd/panic.rs", line 396, in std::panic::catch_unwind
  File "src/libstd/rt.rs", line 47, in std::rt::lang_start_internal
  File "<unknown>", line 0, in main
  File "<unknown>", line 0, in __libc_start_main
  File "<unknown>", line 0, in <unknown>
  File "<unknown>", line 0, in <unknown>

The application panicked (crashed).
  overflow when subtracting durations
in src/libcore/option.rs, line 1185
thread: main
```

**Comment by cjbassi** [comment]
Hmm, it looks like we're subtracting a larger duration from a smaller duration in [this](https://github.com/rust-psutil/rust-psutil/blob/master/src/process/process.rs#L127) function. Not quite sure what's causing that.

**Comment by mtrolley** [comment]
Let me know if there's any environment info you need. I installed using Homebrew on Ubuntu 18.04.

**Comment by matthiaskrgr** [comment]
In case it helps, I managed to repro (wait long enough) with full debuginfo:

````
Backtrace (most recent call first):
  File "src/libcore/option.rs", line 1191, in core::option::expect_failed
  File "src/libcore/option.rs", line 347, in core::option::Option<T>::expect
  File "src/libcore/time.rs", line 753, in <core::time::Duration as core::ops::arith::Sub>::sub
  File "/home/matthias/.cargo/git/checkouts/rust-psutil-b7c53c3e828a6c66/d16e3f7/src/utils.rs", line 40, in psutil::utils::calculate_cpu_percent
    (((second - first).as_nanos() as f64 / total_diff.as_nanos() as f64) * 100.0) as f32
  File "/home/matthias/.cargo/git/checkouts/rust-psutil-b7c53c3e828a6c66/d16e3f7/src/process/process.rs", line 130, in psutil::process::process::Process::cpu_percent
    let percent = calculate_cpu_percent(self.busy, busy, instant - self.instant);
  File "src/widgets/proc.rs", line 232, in <ytop::widgets::proc::ProcWidget as ytop::update::UpdatableWidget>::update::{{closure}}
    cpu: process.cpu_percent()? / cpu_count,
  File "rust:src/libcore/iter/adapters/mod.rs", line 779, in core::iter::adapters::map_try_fold::{{closure}}
  File "rust:src/libcore/iter/traits/iterator.rs", line 1876, in core::iter::traits::iterator::Iterator::try_fold
  File "rust:src/libcore/iter/adapters/mod.rs", line 805, in <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
  File "rust:src/libcore/iter/traits/iterator.rs", line 2204, in core::iter::traits::iterator::Iterator::find_map
  File "rust:src/libcore/iter/adapters/mod.rs", line 1070, in <core::iter::adapters::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next
  File "rust:src/liballoc/vec.rs", line 2131, in alloc::vec::Vec<T>::extend_desugared
  File "rust:src/liballoc/vec.rs", line 2024, in <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend
  File "rust:src/liballoc/vec.rs", line 2019, in <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  File "rust:src/liballoc/vec.rs", line 1919, in <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
  File "rust:src/libcore/iter/traits/iterator.rs", line 1658, in core::iter::traits::iterator::Iterator::collect
  File "src/widgets/proc.rs", line 218, in <ytop::widgets::proc::ProcWidget as ytop::update::UpdatableWidget>::update
    self.procs = self
  File "src/update.rs", line 30, in ytop::update::update_widgets
    widget.update();
  File "src/main.rs", line 147, in ytop::main
    update_widgets(&mut app.widgets, update_seconds);

The application panicked (crashed).
  overflow when subtracting durations
in src/libcore/time.rs, line 753
thread: main
````

**Comment by amyspark** [comment]
@cjbassi Leave ytop running and hibernate computer for at least half a day. (I left it before going to sleep, and when I came back in the morning, it had crashed with this stacktrace.)

**Comment by cjbassi** [comment]
All right, it should be fixed in master and in the latest release. If not, let me know and I'll reopen this.

**Comment by mtrolley** [comment]
Up updated to v0.4.1 and it crashed again with the same issue but a bit different stack:

```
Backtrace (most recent call first):
  File "src/libcore/option.rs", line 1188, in core::option::expect_failed
  File "src/libcore/option.rs", line 348, in core::option::Option<T>::expect
  File "src/libcore/time.rs", line 756, in <core::time::Duration as core::ops::arith::Sub>::sub
  File "<unknown>", line 0, in psutil::cpu::cpu_times_percent::calculate_cpu_times_percent
  File "<unknown>", line 0, in <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  File "<unknown>", line 0, in psutil::cpu::cpu_times_percent::CpuTimesPercentCollector::cpu_times_percent_percpu
  File "<unknown>", line 0, in psutil::cpu::cpu_percent::CpuPercentCollector::cpu_percent_percpu
  File "<unknown>", line 0, in <ytop::widgets::cpu::CpuWidget as ytop::update::UpdatableWidget>::update
  File "<unknown>", line 0, in ytop::update::update_widgets
  File "<unknown>", line 0, in ytop::main
  File "<unknown>", line 0, in std::rt::lang_start::{{closure}}
  File "src/libstd/rt.rs", line 52, in std::rt::lang_start_internal::{{closure}}
  File "src/libstd/panicking.rs", line 292, in std::panicking::try::do_call
  File "src/libpanic_unwind/lib.rs", line 78, in __rust_maybe_catch_panic
  File "src/libstd/panicking.rs", line 270, in std::panicking::try
  File "src/libstd/panic.rs", line 394, in std::panic::catch_unwind
  File "src/libstd/rt.rs", line 51, in std::rt::lang_start_internal
  File "<unknown>", line 0, in main
  File "<unknown>", line 0, in __libc_start_main
  File "<unknown>", line 0, in <unknown>
  File "<unknown>", line 0, in <unknown>

The application panicked (crashed).
  overflow when subtracting durations
in src/libcore/option.rs, line 1188
thread: main
```

Should I report this as a new issue, or reopen this one?

**Comment by cjbassi** [comment]
Hmm, that's interesting. We can just reopen this one for now. I might have had the wrong idea about the original issue and this is just the original issue popping up in a different area.

**Comment by cjbassi** [comment]
@trolley Is it crashing after waking from hibernation or from suspension too?

So it seems like for some reason Linux is reporting lower CPU times at some point when ytop is running. I'm not really sure why it would be doing that. But I'm sure I can work around it now that I know what's happening.

**Comment by mtrolley** [comment]
No, this is on my desktop workstation that's running 24/7. I have tmux running with ytop in one pane and I'll switch to a different window then come back to it crashed.

**Comment by cjbassi** [comment]
All right, it should be fixed in master now. Of course, if theres still issues, let me know and I'll reopen this :sweat_smile:

**Comment by mtrolley** [comment]
@cjbassi Thanks. I'm installing using Homebrew so I'll wait for a new release an try it again :)

**Comment by zicklag** [comment]
Ah, I just tried this and it lasted longer than it did before the change, but it still crashed later:

```
Backtrace (most recent call first):
  File "src/libcore/option.rs", line 1187, in core::option::expect_failed
  File "src/libcore/option.rs", line 347, in core::option::Option<T>::expect
  File "src/libcore/time.rs", line 744, in <core::time::Duration as core::ops::arith::Sub>::sub
  File "<unknown>", line 0, in psutil::cpu::cpu_times_percent::calculate_cpu_times_percent
  File "<unknown>", line 0, in <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  File "<unknown>", line 0, in psutil::cpu::cpu_times_percent::CpuTimesPercentCollector::cpu_times_percent_percpu
  File "<unknown>", line 0, in psutil::cpu::cpu_percent::CpuPercentCollector::cpu_percent_percpu
  File "<unknown>", line 0, in <ytop::widgets::cpu::CpuWidget as ytop::update::UpdatableWidget>::update
  File "<unknown>", line 0, in ytop::update::update_widgets
  File "<unknown>", line 0, in ytop::main
  File "<unknown>", line 0, in std::rt::lang_start::{{closure}}
  File "src/libstd/rt.rs", line 48, in std::rt::lang_start_internal::{{closure}}
  File "src/libstd/panicking.rs", line 287, in std::panicking::try::do_call
  File "src/libpanic_unwind/lib.rs", line 81, in __rust_maybe_catch_panic
  File "src/libstd/panicking.rs", line 265, in std::panicking::try
  File "src/libstd/panic.rs", line 395, in std::panic::catch_unwind
  File "src/libstd/rt.rs", line 47, in std::rt::lang_start_internal
  File "<unknown>", line 0, in main
  File "<unknown>", line 0, in __libc_start_main
  File "<unknown>", line 0, in _start
  File "<unknown>", line 0, in <unknown>

The application panicked (crashed).
  overflow when subtracting durations
in src/libcore/option.rs, line 1187
thread: main
```

> **PS:** Thank you for pointing me to the `better_panic` crate. ;) Now I'm using it in my project instead of `colored-backtrace`. Those are very nice panic messages.

**Comment by cjbassi** [comment]
Are you running any vm's by any chance?

**Comment by zicklag** [comment]
Yep I've got an Ubuntu Vagrant machine running.

**Comment by mtrolley** [comment]
I have a Windows VM running in VMWare Workstation.

**Comment by cjbassi** [comment]
All right I just pushed another fix if someone would be so kind as to test it out :)

**Comment by zicklag** [comment]
Sure thing. In the last couple days I've been using it to monitor my machine that I frequently max the memory out on. I'll let you know how it goes. :+1:

**Comment by zicklag** [comment]
I think it worked. I've been running it almost all day. Earlier I would have gotten about two crashes in that time. :slightly_smiling_face:

**Comment by cjbassi** [comment]
Cool! Closing this, hopefully for the last time.
